version: "3.8"
services:
  geopoc-manage:
    container_name: geopoc-manage
    build:
      context: .
      dockerfile: ./Dockerfile.local
    env_file:
      - ./.env.geoserver
    volumes:
      # This volume should be included by the built image (here only for dev usage)
      - ./data_dir:/opt/geoserver/data_dir
      # External data
      - ./data:/opt/geoserver/data_dir/data
      # JNDI Configuration
      # - ./tomcat/context.xml:/usr/local/tomcat/conf/context.xml
      # Logs
      # - ./logs:/opt/geoserver/data_dir/logs
    ports:
      - 8082:8080
    networks:
      - default
  geowebcache:
    container_name: geowebcache
    build:
      context: ./geowebcache
      dockerfile: ./Dockerfile.local
      args:
        - GWC_VERSION=1.18.4
    env_file:
      - ./.env.geowebcache
    volumes:
      # This volume should be included by the built image (here only for dev usage)
      - ./geowebcache/configuration:/usr/local/tomcat/temp/geowebcache
      # Set this volume on server side to be any SUN/NFS disk etc.
      - ./geowebcache/cache:/tmp/defaultCache
    ports:
      - 8080:8080
    networks:
      - default